name: obsidian-export
on:
  [push]
  # schedule:
  #   # 定期実行する時間・・・①
  #   - cron: '0 9 * * *'

jobs:
  cloudflare-r2:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest
    steps:
      - name: Get R2 bucket usage
        id: get_r2-bucket-usage
        env:
          ACCOUNT_ID: ${{ secrets.account_id }}
          BUCKET_NAME: ${{ secrets.bucket_name }}
          API_TOKEN: ${{ secrets.api_token }}
        run: |
        RESPONSE=$(curl -X GET "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/r2/buckets/$BUCKET_NAME/usage" \
        -H "Authorization: Bearer $API_TOKEN" \
        -H "Content-Type:application/json")
        echo "RESPONSE_JSON=$RESPONSE" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/zoni/obsidian-export/releases/download/v23.12.0/obsidian-export-x86_64-pc-windows-msvc.zip"
          name: "obsidian-export"
          version: "0.0.1"
          command: ./obsidian-export/obsidian-export

      - name: test    
        run: ls -la      
